In [16]:
import pandas as pd

In [17]:
df = pd.read_excel("../excel/dataupdate.xlsx","weather",index_col="Day")
df[df.Temperature<=20]

            Temperature  WindSpeed    Event
Day
2020-12-04           19          3  แดดร้อน
2020-12-05           20          5   เมฆมาก
2020-12-09           17          5   เมฆมาก
2020-12-17           20          8     ฝนตก
2020-12-18           18          5     ฝนตก

In [18]:
df[df.Event == "แดดร้อน"]

            Temperature  WindSpeed    Event
Day
2020-12-01           30          9  แดดร้อน
2020-12-04           19          3  แดดร้อน
2020-12-10           24          6  แดดร้อน
2020-12-12           27          9  แดดร้อน
2020-12-13           30          2  แดดร้อน
2020-12-15           28          4  แดดร้อน
2020-12-16           27          7  แดดร้อน
2020-12-19           25          7  แดดร้อน
2020-12-25           34          5  แดดร้อน

In [19]:
df.loc[(df.Event == "ฝนตก") & (df.Temperature >= 30)]

            Temperature  WindSpeed Event
Day
2020-12-07           36          4  ฝนตก
2020-12-23           34          3  ฝนตก
2020-12-29           31          1  ฝนตก
2020-12-30           35          2  ฝนตก

In [20]:
df.loc[(df.Event == "เมฆมาก") | (df.Temperature <= 18)]

            Temperature  WindSpeed   Event
Day
2020-12-02           28          8  เมฆมาก
2020-12-05           20          5  เมฆมาก
2020-12-09           17          5  เมฆมาก
2020-12-14           31          5  เมฆมาก
2020-12-18           18          5    ฝนตก
2020-12-20           28          4  เมฆมาก
2020-12-21           25          5  เมฆมาก
2020-12-22           38          2  เมฆมาก
2020-12-27           28          9  เมฆมาก
2020-12-28           30          2  เมฆมาก

In [21]:
df.loc[(df.Temperature == 18) | (df.Temperature == 20) | (df.Temperature == 25) | (df.Temperature == 35) ]

            Temperature  WindSpeed    Event
Day
2020-12-05           20          5   เมฆมาก
2020-12-06           25          6     ฝนตก
2020-12-17           20          8     ฝนตก
2020-12-18           18          5     ฝนตก
2020-12-19           25          7  แดดร้อน
2020-12-21           25          5   เมฆมาก
2020-12-26           25          8     ฝนตก
2020-12-30           35          2     ฝนตก

In [22]:
df.loc[(df.Temperature.isin([18,20,25,35,31]))]

            Temperature  WindSpeed    Event
Day
2020-12-05           20          5   เมฆมาก
2020-12-06           25          6     ฝนตก
2020-12-14           31          5   เมฆมาก
2020-12-17           20          8     ฝนตก
2020-12-18           18          5     ฝนตก
2020-12-19           25          7  แดดร้อน
2020-12-21           25          5   เมฆมาก
2020-12-26           25          8     ฝนตก
2020-12-29           31          1     ฝนตก
2020-12-30           35          2     ฝนตก

In [23]:
df.loc[(df.Temperature.isin([30,35]))]

            Temperature  WindSpeed    Event
Day
2020-12-01           30          9  แดดร้อน
2020-12-13           30          2  แดดร้อน
2020-12-28           30          2   เมฆมาก
2020-12-30           35          2     ฝนตก

In [27]:
df.loc[(df.Temperature.isin([25,30]))][df.Event == "แดดร้อน"]

C:\Users\mcftt\AppData\Local\Temp\ipykernel_7516\1936989571.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df.loc[(df.Temperature.isin([25,30]))][df.Event == "แดดร้อน"]

            Temperature  WindSpeed    Event
Day
2020-12-01           30          9  แดดร้อน
2020-12-13           30          2  แดดร้อน
2020-12-19           25          7  แดดร้อน